site_name: 2025-Yatcpu-Fall-Docs
site_author: Tokisakix
copyright: Copyright Â© 2023 Tokisakix

nav:
- å‰è¨€: docs/index.md


- æœ€ç»ˆéªŒæ”¶: docs/test.md
- docs/better-tut/intro.md
- å®éªŒç¯å¢ƒé…ç½®:
  - docs/better-tut/getting-started/index.md
  - docs/better-tut/getting-started/windows.md
  - docs/better-tut/getting-started/linux-wsl.md
  - docs/better-tut/getting-started/macos.md
  # - docs/better-tut/getting-started/docker.md
  - ä¸€é”®é…ç½® docker ç¯å¢ƒ: docs/env.md

- åŸºç¡€å·¥ç¨‹çŸ¥è¯†ä¸æŠ€èƒ½:
  - docs/better-tut/practice/envvar-and-cmd.md
  - docs/better-tut/practice/scala-and-chisel.md
  - docs/better-tut/practice/chisel-test.md
  - docs/better-tut/practice/simulation.md
  - docs/better-tut/practice/compliance-test.md
  - docs/better-tut/practice/coremark-benchmark.md
  - docs/better-tut/practice/program-device.md
  - docs/better-tut/practice/hardware-debug.md
  - docs/better-tut/practice/compile-and-link.md
  - docs/better-tut/practice/cmake.md
  - å¦‚ä½•ä¸€é”®çƒ§æ¿: board.md
  
- ç†è®ºçŸ¥è¯†åŸºç¡€:
  - docs/better-tut/theory/cpu-arch.md
  - docs/better-tut/theory/riscv-isa.md
  - docs/better-tut/theory/interrupt-and-exception.md
  - docs/better-tut/theory/bus.md
- å®éªŒ:
  - docs/better-tut/labs/lab1/lab1-single-cycle-cpu.md
  - docs/better-tut/labs/lab2/lab2-interrupt.md
  - docs/better-tut/labs/lab3/lab3-pipelined-cpu.md
  - docs/better-tut/labs/lab4/lab4-bus.md
  - docs/better-tut/labs/challenge1/challenge1-running-os.md
- å¿«é€Ÿå‚è€ƒèµ„æ–™:
  - docs/better-tut/cheatsheets/riscv-isa.md
  - docs/better-tut/cheatsheets/ide-tips.md
- docs/references.md
- docs/acknowledgement.md

theme:
  name: material
  features:
    - content.tabs.link
    - navigation.expand

use_directory_urls: false
markdown_extensions:
  - toc:
      permalink: "ğŸš"
  - pymdownx.superfences
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - tables
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.keys

plugins:
  - glightbox:
      zoomable: true
      width: 100%